export { default as DashboardTab, type DashStats } from './DashboardTab'
export { default as DispatchTab } from './DispatchTab'
export { default as WeighbridgeTab } from './WeighbridgeTab'
export { default as BookingsTab } from './BookingsTab'
export { default as CustomersTab } from './CustomersTab'
export { default as ReportsTab } from './ReportsTab'
export { default as InventoryTab } from './InventoryTab'
export { default as FleetTab } from './FleetTab'
export { default as MapTab } from './MapTab'
export { default as SettingsTab } from './SettingsTab'
